package model;
// Generated 14-may-2015 16:14:39 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DetalleLeccion generated by hbm2java
 */
@Entity
@Table(name="detalle_leccion"
    ,catalog="tesis"
)
public class DetalleLeccion  implements java.io.Serializable {


     private Integer iddetalleLeccion;
     private String numeroPregunta;
     private String pregunta;
     private String respuesta;
     private String estado;
     private String mensaje;
     private String observacion;
     private String puntuacion;
     private Set leccions = new HashSet(0);

    public DetalleLeccion() {
    }

    public DetalleLeccion(String numeroPregunta, String pregunta, String respuesta, String estado, String mensaje, String observacion, String puntuacion, Set leccions) {
       this.numeroPregunta = numeroPregunta;
       this.pregunta = pregunta;
       this.respuesta = respuesta;
       this.estado = estado;
       this.mensaje = mensaje;
       this.observacion = observacion;
       this.puntuacion = puntuacion;
       this.leccions = leccions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="iddetalle_leccion", unique=true, nullable=false)
    public Integer getIddetalleLeccion() {
        return this.iddetalleLeccion;
    }
    
    public void setIddetalleLeccion(Integer iddetalleLeccion) {
        this.iddetalleLeccion = iddetalleLeccion;
    }
    
    @Column(name="numero_pregunta", length=45)
    public String getNumeroPregunta() {
        return this.numeroPregunta;
    }
    
    public void setNumeroPregunta(String numeroPregunta) {
        this.numeroPregunta = numeroPregunta;
    }
    
    @Column(name="pregunta", length=45)
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }
    
    @Column(name="respuesta", length=45)
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }
    
    @Column(name="estado", length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    @Column(name="mensaje", length=45)
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }
    
    @Column(name="observacion", length=45)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    
    @Column(name="puntuacion", length=45)
    public String getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(String puntuacion) {
        this.puntuacion = puntuacion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detalleLeccion")
    public Set getLeccions() {
        return this.leccions;
    }
    
    public void setLeccions(Set leccions) {
        this.leccions = leccions;
    }




}


