package model;
// Generated 14-may-2015 16:14:39 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name="docente"
    ,catalog="tesis"
)
public class Docente  implements java.io.Serializable {


     private Integer iddocente;
     private Usuario usuario;
     private String nombre;
     private String apellido;
     private Integer dni;

    public Docente() {
    }

	
    public Docente(Usuario usuario) {
        this.usuario = usuario;
    }
    public Docente(Usuario usuario, String nombre, String apellido, Integer dni) {
       this.usuario = usuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="iddocente", unique=true, nullable=false)
    public Integer getIddocente() {
        return this.iddocente;
    }
    
    public void setIddocente(Integer iddocente) {
        this.iddocente = iddocente;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_idusuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="apellido", length=45)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    
    @Column(name="dni")
    public Integer getDni() {
        return this.dni;
    }
    
    public void setDni(Integer dni) {
        this.dni = dni;
    }




}


