package model;
// Generated 14-may-2015 16:14:39 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nivel generated by hbm2java
 */
@Entity
@Table(name="nivel"
    ,catalog="tesis"
)
public class Nivel  implements java.io.Serializable {


     private Integer idnivel;
     private Leccion leccion;
     private String nivel;
     private String tema;
     private Set cursos = new HashSet(0);

    public Nivel() {
    }

	
    public Nivel(Leccion leccion) {
        this.leccion = leccion;
    }
    public Nivel(Leccion leccion, String nivel, String tema, Set cursos) {
       this.leccion = leccion;
       this.nivel = nivel;
       this.tema = tema;
       this.cursos = cursos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idnivel", unique=true, nullable=false)
    public Integer getIdnivel() {
        return this.idnivel;
    }
    
    public void setIdnivel(Integer idnivel) {
        this.idnivel = idnivel;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="leccion_idleccion", nullable=false)
    public Leccion getLeccion() {
        return this.leccion;
    }
    
    public void setLeccion(Leccion leccion) {
        this.leccion = leccion;
    }
    
    @Column(name="nivel", length=45)
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    
    @Column(name="tema", length=45)
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="nivel")
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }




}


